import type { LibraryItem, ZoneType } from './types';

const zonePreference = (...preferredZoneTypes: ZoneType[]) => ({
  preferredZoneTypes,
});

export const libraryItems: LibraryItem[] = [
  {
    id: 'desk-single',
    type: 'desk-single',
    name: '1人用デスク',
    category: 'desk',
    width: 1400,
    height: 700,
    seatCount: 1,
    fill: '#bfdbfe',
    stroke: '#1d4ed8',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['bottom'],
      localChairSides: ['bottom'],
      ...zonePreference('work', 'focus'),
      tags: ['desk', 'focus'],
    },
  },
  {
    id: 'desk-island-4',
    type: 'desk-island-4',
    name: '4人島',
    category: 'desk',
    width: 2800,
    height: 1400,
    seatCount: 4,
    fill: '#93c5fd',
    stroke: '#2563eb',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['left', 'right'],
      localChairSides: ['top', 'bottom'],
      ...zonePreference('work'),
      tags: ['desk', 'collaboration'],
    },
  },
  {
    id: 'desk-free-address',
    type: 'desk-free-address',
    name: 'フリーアドレス島',
    category: 'desk',
    width: 3200,
    height: 1600,
    seatCount: 6,
    fill: '#60a5fa',
    stroke: '#1d4ed8',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['left', 'right'],
      localChairSides: ['top', 'bottom'],
      ...zonePreference('work'),
      tags: ['desk', 'free-address'],
    },
  },
  {
    id: 'meeting-4',
    type: 'meeting-4',
    name: '4人会議テーブル',
    category: 'meeting',
    width: 1800,
    height: 900,
    seatCount: 4,
    fill: '#c4b5fd',
    stroke: '#7c3aed',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['top', 'right', 'bottom', 'left'],
      localChairSides: ['top', 'right', 'bottom', 'left'],
      meetingEntrySides: ['left', 'right'],
      ...zonePreference('meeting'),
      tags: ['meeting'],
    },
  },
  {
    id: 'meeting-6',
    type: 'meeting-6',
    name: '6人会議テーブル',
    category: 'meeting',
    width: 2400,
    height: 1100,
    seatCount: 6,
    fill: '#a78bfa',
    stroke: '#6d28d9',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['top', 'right', 'bottom', 'left'],
      localChairSides: ['top', 'right', 'bottom', 'left'],
      meetingEntrySides: ['left', 'right'],
      ...zonePreference('meeting'),
      tags: ['meeting'],
    },
  },
  {
    id: 'storage-cabinet',
    type: 'storage-cabinet',
    name: '収納',
    category: 'storage',
    width: 1200,
    height: 450,
    seatCount: 0,
    fill: '#fed7aa',
    stroke: '#ea580c',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['bottom'],
      keepNearWall: true,
      ...zonePreference('support'),
      tags: ['storage'],
    },
  },
  {
    id: 'locker',
    type: 'locker',
    name: 'ロッカー',
    category: 'storage',
    width: 1800,
    height: 500,
    seatCount: 0,
    fill: '#fdba74',
    stroke: '#c2410c',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['bottom'],
      keepNearWall: true,
      ...zonePreference('support'),
      tags: ['storage'],
    },
  },
  {
    id: 'copier',
    type: 'copier',
    name: 'コピー機',
    category: 'support',
    width: 1000,
    height: 700,
    seatCount: 0,
    fill: '#cbd5e1',
    stroke: '#475569',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['bottom'],
      frontOperationSide: 'bottom',
      frontOperationDepth: 900,
      keepNearWall: true,
      ...zonePreference('support'),
      tags: ['support'],
    },
  },
  {
    id: 'reception-counter',
    type: 'reception-counter',
    name: '受付カウンター',
    category: 'reception',
    width: 2400,
    height: 800,
    seatCount: 0,
    fill: '#86efac',
    stroke: '#15803d',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['bottom'],
      waitingAreaSide: 'bottom',
      waitingAreaDepth: 1400,
      keepNearWall: true,
      ...zonePreference('reception'),
      tags: ['reception'],
    },
  },
  {
    id: 'sofa',
    type: 'sofa',
    name: 'ソファ',
    category: 'lounge',
    width: 1800,
    height: 900,
    seatCount: 3,
    fill: '#fbcfe8',
    stroke: '#db2777',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['bottom'],
      ...zonePreference('lounge', 'reception'),
      tags: ['lounge'],
    },
  },
  {
    id: 'work-booth',
    type: 'work-booth',
    name: 'ワークブース',
    category: 'support',
    width: 1400,
    height: 1400,
    seatCount: 1,
    fill: '#bfdbfe',
    stroke: '#0369a1',
    origin: 'preset',
    metadata: {
      localCorridorSides: ['bottom'],
      ...zonePreference('focus', 'work'),
      tags: ['booth'],
    },
  },
  {
    id: 'column',
    type: 'column',
    name: '柱',
    category: 'structure',
    width: 700,
    height: 700,
    seatCount: 0,
    fill: '#e2e8f0',
    stroke: '#64748b',
    origin: 'preset',
    metadata: {
      tags: ['structure'],
    },
  },
  {
    id: 'door-marker',
    type: 'door-marker',
    name: '扉マーカー',
    category: 'structure',
    width: 900,
    height: 150,
    seatCount: 0,
    fill: '#fef3c7',
    stroke: '#ca8a04',
    origin: 'preset',
    metadata: {
      keepNearWall: true,
      tags: ['door', 'structure'],
    },
  },
  {
    id: 'obstacle',
    type: 'obstacle',
    name: '障害物',
    category: 'structure',
    width: 1000,
    height: 1000,
    seatCount: 0,
    fill: '#fecaca',
    stroke: '#b91c1c',
    origin: 'preset',
    metadata: {
      tags: ['obstacle'],
    },
  },
];
