import type { LibraryItem } from "./types";

export const LIBRARY: LibraryItem[] = [
  {
    id: "desk1",
    kind: "desk1",
    label: "1人用デスク",
    defaultWidth: 1200,
    defaultHeight: 700,
    seats: 1,
    chairClearance: 600,
    category: "desk",
  },
  {
    id: "desk-island-4",
    kind: "desk-island-4",
    label: "4人島",
    defaultWidth: 2400,
    defaultHeight: 1400,
    seats: 4,
    chairClearance: 600,
    category: "desk",
  },
  {
    id: "desk-island-free",
    kind: "desk-island-free",
    label: "フリーアドレス島",
    defaultWidth: 3600,
    defaultHeight: 1400,
    seats: 6,
    chairClearance: 600,
    category: "desk",
  },
  {
    id: "meeting-4",
    kind: "meeting-4",
    label: "4人会議テーブル",
    defaultWidth: 1800,
    defaultHeight: 1200,
    seats: 4,
    chairClearance: 700,
    category: "meeting",
  },
  {
    id: "meeting-6",
    kind: "meeting-6",
    label: "6人会議テーブル",
    defaultWidth: 2400,
    defaultHeight: 1200,
    seats: 6,
    chairClearance: 700,
    category: "meeting",
  },
  {
    id: "storage",
    kind: "storage",
    label: "収納",
    defaultWidth: 900,
    defaultHeight: 450,
    frontClearance: 700,
    category: "storage",
  },
  {
    id: "locker",
    kind: "locker",
    label: "ロッカー",
    defaultWidth: 900,
    defaultHeight: 450,
    frontClearance: 700,
    category: "storage",
  },
  {
    id: "copier",
    kind: "copier",
    label: "コピー機",
    defaultWidth: 800,
    defaultHeight: 700,
    frontClearance: 1000,
    category: "service",
  },
  {
    id: "reception",
    kind: "reception",
    label: "受付カウンター",
    defaultWidth: 1800,
    defaultHeight: 700,
    frontClearance: 1500,
    category: "service",
  },
  {
    id: "sofa",
    kind: "sofa",
    label: "ソファ",
    defaultWidth: 1800,
    defaultHeight: 800,
    seats: 3,
    category: "lounge",
  },
  {
    id: "booth",
    kind: "booth",
    label: "ワークブース",
    defaultWidth: 1100,
    defaultHeight: 1100,
    seats: 1,
    category: "lounge",
  },
  {
    id: "pillar",
    kind: "pillar",
    label: "柱",
    defaultWidth: 600,
    defaultHeight: 600,
    category: "structure",
  },
  {
    id: "door",
    kind: "door",
    label: "扉",
    defaultWidth: 900,
    defaultHeight: 200,
    frontClearance: 900,
    category: "structure",
  },
  {
    id: "obstacle",
    kind: "obstacle",
    label: "障害物",
    defaultWidth: 800,
    defaultHeight: 800,
    category: "structure",
  },
];

export function libraryItemByKind(kind: string): LibraryItem | undefined {
  return LIBRARY.find((item) => item.kind === kind);
}
